name: Java CI

on:
  push:
    branches:
      - master

jobs:
  main_step:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn compile --file pom.xml
      - name: Integration Test
        run: mvn test --file pom.xml
